# Generated by Django 5.1.7 on 2025-03-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintable',
            name='address',
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='logintable',
            name='status',
        ),
        migrations.AlterField(
            model_name='logintable',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
