# Generated by Django 5.1.7 on 2025-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_logintable_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_NAME', models.CharField(max_length=30, null=True)),
                ('CAT_IMG', models.ImageField(null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_NAME', models.CharField(max_length=40, null=True)),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('PHONE_NO', models.BigIntegerField()),
                ('PASSWORD', models.CharField(max_length=8, null=True)),
                ('U_ADDRESS', models.TextField(null=True)),
                ('U_GENDER', models.CharField(max_length=30, null=True)),
                ('STATUS', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='logintable',
        ),
    ]
