# Generated by Django 5.1.7 on 2025-04-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='SELLER_ID',
        ),
    ]
