# Generated by Django 5.1.7 on 2025-04-03 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_product_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUANTITY', models.IntegerField(null=True)),
                ('Totalamount', models.IntegerField()),
                ('Cart_STATUS', models.IntegerField()),
                ('ORDER_ID', models.IntegerField()),
                ('SHIPPING_CHARGE', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('LOGIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('PROD_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FINALTOTAL', models.IntegerField(null=True)),
                ('PAY_MODE', models.CharField(max_length=40, null=True)),
                ('NAME', models.CharField(max_length=40, null=True)),
                ('ADDRESS', models.TextField(null=True)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('LOGIN_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
