# Generated by Django 5.1.7 on 2025-04-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cartable_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=30, null=True)),
                ('U_NAME', models.CharField(max_length=30, null=True)),
                ('Email_ID', models.EmailField(max_length=254, null=True)),
                ('Phone_NO', models.BigIntegerField(null=True)),
                ('MESSAGE', models.TextField()),
                ('TIMESTAMP', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
