# Generated by Django 5.1.7 on 2025-04-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TIMESTAMP',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
