# Generated by Django 5.1.7 on 2025-04-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PAYMENT_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='PAY_MODE',
            field=models.CharField(choices=[('cod', 'COD'), ('paynow', 'Online Payment')], max_length=20),
        ),
    ]
